FROM golang:1.11.4-alpine
RUN apk add --update --no-cache git
RUN go get github.com/spf13/viper 
RUN go get github.com/gorilla/handlers 
RUN go get github.com/gorilla/mux 
RUN go get github.com/go-sql-driver/mysql 
RUN go get github.com/gosimple/slug 
RUN go get gopkg.in/redis.v5 
RUN go get golang.org/x/net/html
RUN go get github.com/yvasiyarov/php_session_decoder/php_serialize
