version: '3'
services:
    web:
        container_name: nginx
        image: nginx:alpine
        volumes:
            - ./www:/var/www/html
            - ./config/nginx:/etc/nginx/conf.d
            - ./config/ssl:/etc/nginx/ssl
            - ./config/log:/var/log/nginx
        ports:
        #    - "80:80"
            - "443:443"
        working_dir: /var/www/html
        links:
            - app
            - go
            - api
    app:
        container_name: shonet-front-php
        image: shonet/front-php:latest
        volumes:
            - ./www:/var/www/html
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
            - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        working_dir: /var/www/html
        links:
            - mysql
            - redis
    go:
        container_name: shonet-front-go
        image: shonet/front-go:latest
        volumes:
            - ./go:/go/src/github.com/jacky-htg/shonet-frontend
        working_dir: /go/src/github.com/jacky-htg/shonet-frontend
        ports:
            - "8080:8080"
        environment:
            - GOPATH=/go
        links:
            - mysql
            - redis
        command: go run main.go
    mysql:
        container_name: mysql
        image: mysql:5.7.20
        ports:
            - "33060:3306"
        volumes:
            - ../mysql_storage:/var/lib/mysql
            - /etc/localtime:/etc/localtime
        environment:
            - "MYSQL_ROOT_PASSWORD=pass"
            - "MYSQL_DATABASE=shonet_dev"
    redis:
        container_name: redis
        image: "redis:alpine"
        ports:
            - "63790:6379"
    api:
        image: shonet/api:latest
        volumes:
            - ./api:/go/src/shonet-api
        working_dir: /go/src/shonet-api
        container_name: shonet-api
        ports:
            - "8081:8081"
        environment:
            - GOPATH=/go
        links:
            - redis
            - mysql
        command: go run main.go
